### ISSUE TITLE
Local own Setup with own Database

### ISSUE THREAD

**Issue by TandelK** [SanketRevankar/TourneyManager#1]
Is there any way we can create own Local Server and Local Database instead of relying on Google Cloud services?

**Comment by SanketRevankar** [comment]
@TandelK You can use your local server with it but to use your own database you will need to rewrite all queries according to the database you will be using.

**Comment by TandelK** [comment]
Is there someway i can get all the queries ? 
Just require Database Structure.

**Comment by SanketRevankar** [comment]
@TandelK 
TourneyManager/util/MySQLHelper.py will contain all the queries to MySQL DB and TourneyManager/util/DataStoreHelper.py will contain all the queries to Google DataStore.
Alternatively you can find them in TourneyManager/constants/StringConstants.py

Regarding DB structure for datastore:
match table - 
Name/ID | ip | map1 | map1_score | map2 | map2_score | map3 | map3_score | start_time | status | team1 | team1_id | team2 | team2_id | team_tag1 | team_tag2 | 

teams table -
Name/ID | team_logo | team_name | team_tag |  

players table -
Name/ID | fb_id | name | reg_time | steam | steam_icon | steam_id | steam_nick | team |  

As for the structure of MySQL DB, it will be auto created the first time the program runs.
